name: toxic
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'openssl'
- !!python/unicode
  'pip=8.1.2=py27_0'
- !!python/unicode
  'python=2.7.12=1'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'setuptools=26.1.1=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - backports.functools-lru-cache==1.4
  - boto==2.48.0
  - boto3==1.5.20
  - botocore==1.8.34
  - bz2file==0.98
  - certifi==2018.1.18
  - chardet==3.0.4
  - cycler==0.10.0
  - docutils==0.14
  - futures==3.2.0
  - gensim==3.2.0
  - idna==2.6
  - jmespath==0.9.3
  - keras==2.1.3
  - matplotlib==2.1.2
  - numpy==1.14.0
  - pandas==0.22.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.3
  - pyyaml==3.12
  - requests==2.18.4
  - s3transfer==0.1.12
  - scikit-learn==0.19.1
  - scipy==1.0.0
  - six==1.11.0
  - sklearn==0.0
  - smart-open==1.5.6
  - subprocess32==3.2.7
  - urllib3==1.22
